Fix for args & target improperly being split
jiri-otoupal/pycrosskit pull request #55
Opened 2023-06-15 13:08 UTC by shivenBajpai

fixes #53, fixes #54 

Contains three changes:

1. Uses regex to fix the #53 as well as a test to check for the same

2. Bumped up isort version in pre-commit-config.yaml, I dont know a lot on the matter but apparently they had a bug on their end that would cause pre-commit hooks to fail and this is the closest version with a fix, [reference ](https://github.com/home-assistant/core/issues/86892)

3. Changed the way the parameters are passed in pycrosskit.Shortcut to fix #54 

:)

2023-06-15 13:16 UTC, jiri-otoupal commented on tests/test_shortcut.py
> +        desktop, _ = Shortcut.delete("SplitTest", desktop=True)
unused var, put `_ ` instead of `desktop`

2023-06-15 13:20 UTC, jiri-otoupal requested changes

2023-06-15 13:40 UTC, shivenBajpai commented
Ok I've done that, and added docstrings for the test because Deepsource wanted me to
seems that renaming the variable of UserFolder to snake case has caused it to put more problems to my name but I had nothing to do with those

2023-06-16 07:27 UTC, jiri-otoupal approved these changes

2023-06-16 07:28 UTC, merged